version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    container_name : nsqlookupd # 设置容器名字
    ports:
    - "4160:4160"
    - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd -data-path=/data --lookupd-tcp-address=nsqlookupd:4160
    container_name : nsqd # 设置容器名字
    volumes:
    - $PWD/nsqd/data:/data
    depends_on:
    - nsqlookupd
    ports:
    - "4150:4150"
    - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    container_name : nsqadmin # 设置容器名字
    depends_on:
    - nsqlookupd
    ports:
    - "4171:4171"